[tools]
"cargo:mdsf" = "latest"# In CI, installed with 'hougesen/mdsf'
"pipx:prek" = "latest"  # In CI, installed with 'j178/prek-action'
"pipx:pytest-watcher" = "latest"
"pipx:tox" = {uvx_args = "--with tox-uv>=1.29.0", version = "4.32.0"}
python = ["3.10.15", "3.14.0"]
uv = "latest"# In CI, installed with 'astral-sh/setup-uv'
